version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: docker_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: heatspots_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - app_network
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker_app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app
    environment:
      FLASK_ENV: development
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:

